### ISSUE TITLE
emqttd not getting all messages when subscriber application is down

### ISSUE THREAD

**Issue by Guna25584** [emqx/emqx-retainer#145]
Only receiving last retained message when subscriber application restarted.

OS: Windows
EMQ Broker version : 2.3.10
Eclipse paho

When I am publishing 10 messages on same topic, during that time for some reason subscriber application crashed, after sometime  sub application restarted, I am getting only last retaining message only and losing all other data which is big problem.

I am putting Retained flag is true , clean session flag as false and Qos as 1 on both pub and sub.

can some one help on this. 
Am I missing any configuration or Erlang broker behaves like getting only last retaining message.

**Comment by HJianBo** [comment]
In the MQTT protocol, the `Retained Message`  just keep the latest message.

>  If the RETAIN flag is set to 1, in a PUBLISH Packet sent by a Client to a Server, the Server MUST store the Application Message and its QoS, so that it can be delivered to future subscribers whose subscriptions match its topic name [MQTT-3.3.1-5]. **When a new subscription is established, the last retained message, if any, on each matching topic name MUST be sent to the subscriber [MQTT-3.3.1-6]**. If the Server receives a QoS 0 message with the RETAIN flag set to 1 it MUST discard any message previously retained for that topic. It SHOULD store the new QoS 0 message as the new retained message for that topic, but MAY choose to discard it at any time - if this happens there will be no retained message for that topic [MQTT-3.3.1-7].

**Comment by Guna25584** [comment]
If Resubscribe happen to same client Id, then able to receive all the messages. if retain flag set to true, only last message will be received. After re subscription happen to same client Id issue has been solved.
Thanks.
