### ISSUE TITLE
Where are the messages stored when selecting disc option in storage_type

### ISSUE THREAD

**Issue by zacsonskaria** [emqx/emqx-retainer#152]
Where are the messages stored when selecting disc option in storage_type? Does it get stored on ram and later moved to disc or does it overflow to disc beyond some limit?

**Comment by HJianBo** [comment]
It will be stored in the `etc/data/mnesia` directory.

> Does it get stored on ram and later moved to disc or does it overflow to disc beyond some limit?
Actually, it does on Mnesia ( it is the erlang's database)  and we don't need to worry about it.

**Comment by zacsonskaria** [comment]
How does it differ from disc_only option? It will be great if you can explain or differentiate further on the 3 options available.

**Comment by HJianBo** [comment]
- **ram_copies.** A table can be replicated on a number of Erlang nodes. Property ram_copies specifies a list of Erlang nodes where RAM copies are kept. These copies can be dumped to disc at regular intervals. However, updates to these copies are not written to disc on a transaction basis.

- **disc_copies.** This property specifies a list of Erlang nodes where the table is kept in RAM and on disc. All updates of the table are performed in the actual table and are also logged to disc. If a table is of type disc_copies at a certain node, the entire table is resident in RAM memory and on disc. Each transaction performed on the table is appended to a LOG file and written into the RAM table.

- **disc_only_copies.** Some, or all, table replicas can be kept on disc only. These replicas are considerably slower than the RAM-based replicas.

**Comment by zacsonskaria** [comment]
Excellent. I have changed storage_type from disc_only_copies to disc_copies, restarted emqx and all the retained messages were moved seamlessly to the RAM with copies available on disc. There is also a significance improvement in message delivery.
Those of who would like to understand further on these can read about mnesia at https://erlang.org/doc/man/mnesia.html
