### ISSUE TITLE
Feature Request - Message Level TTL for Retained MQTT Message

### ISSUE THREAD

**Issue by louis-wangxiao** [emqx/emqx-retainer#52]
We're now using the `Global Level` configuration `retainer.expiry_interval` to configure the TTL of a retained message.

But does EMQ support something like `Message Level` configuration about that? I want to configure TTL per message.

**Comment by terry-xiaoyu** [comment]
This feature is included in MQTT 5.0 and has been implemented in EMQ X 3.0-beta.2.
