### ISSUE TITLE
What an interesting piece of softwzre

### ISSUE THREAD

**Issue by PythonLinks** [emqx/emqx-retainer#65]
I wish I had found it a year ago. 

Can you add a little more to the documentation?

How does this work?  How does it share data across RAM and hard drive. 
If the server crashes, is the data backed up?
Is there any api?  Can I edit the data files?
Are there data files. 

Right now it just appears to me to be a black box, so I have no judgement on how it performs, 
how well it distributes, what its limitations are. 

Tough to decide if I should use it or not.

I am tempted to use topic tracing to a RAM disk.  How does this ocmpare?

**Comment by sgaoemq** [comment]
Please check out our documentations and feel free to ask our questions via Slack channels
https://developer.emqx.io/docs/emq/v3/en/
