### ISSUE TITLE
Storage path name problem in restart

### ISSUE THREAD

**Issue by berk-can** [emqx/emqx-retainer#66]
We try to use emqtt in kubernetes with glusterFs by using storage_type=disc but folder is created differently as 'emqtt@<IP>' in restart of service because Ip address changes.
So we try to give IP address as 0.0.0.0 so that it would be same after every restart but still we cannot use retain folder after reboot,
Is there something we are doing wrong or is there a way to reuse retain messages on restart of emqtt

**Comment by zhanghongtong** [comment]
We do not recommend storing messages on disk in kubernetes.

**Comment by berk-can** [comment]
my colleague have recently managed to store in disk via GlusterFs and was able to recover after recreating statefulSet, can you elaborate why you do not recommend this, what problems can we encounter?

**Comment by zhanghongtong** [comment]
First, in kubernetes, if you want to save the message to disk in emqx crash, you only need to save the last crash pod, but you can't know which pod will crash in advance.
Second, if you want to reuse the reserved message when you restart emqx, you must ensure that the information such as `nodeName` is the same, but the IP of each pod in the kubernetes deployment is different, so the consistency of `nodeName` cannot be guaranteed.
So, if you want to keep messages in kubernetes, you can bridge to third-party services, or use our enterprise version of the solution, emqx Enterprise Edition supports mysql, pgsql, mongoDB, kafka, redis and other message storage solutions
In addition, this is my understanding, if your colleagues have a better solution, welcome to share with us.

**Comment by berk-can** [comment]
I learnt that he made it possible by giving dns name provided by kube-dns which resolves into internal IP of emqtt pod, we couldnt produce emqtt pod crash case otherwise it works very well, thanks for the help
